### ISSUE TITLE
Opening connection...

### ISSUE THREAD

**Issue by FacundoCorrea** [zafartahirov/fingerpi#12]
When I run demo.py it prints in console
Opening connection...
And stucks in there
What would it be?

**Comment by achraf-boussaada** [comment]
Hi ,
any update on this ... i have the same problem

**Comment by zafartahirov** [comment]
The `fingerpi` iterates through all possible baudrates, and finds the ones that are suited. If your port is not specified in here https://github.com/zafartahirov/fingerpi/blob/93c91ec023d50668f817daefb369cf9e6e30b535/demo.py#L28 meaning you are using the default port (`/dev/ttyAMA0`), it will never find the suitable baudarate, and will be stuck there for some time. 

In your case, the problem is that your sensor is not connected properly to the R-Pi. It could be different port number, unsupported baudrate, or just wiring not right. Also, you HAVE TO make sure your R-Pi have enabled serial port!

Try using `interactive.py` if you are debugging your setup.
