### ISSUE TITLE
Script it's not working

### ISSUE THREAD

**Issue by eron93br** [zafartahirov/fingerpi#5]
Hello zafartahirov,

I'm trying to run your script demo.py to my current application. I need to get the image from this sensor. 

I've already tried to run demo.py on Raspberry Pi 2 and RPi Zero! On both plataforms the code is not working. It's appears "Unknown error code".  

I've doubled check the wiring and is everything correct. 

Could you provide any explication of common errors of the usage of your code based on your own experience?

Thanks very much for your contribution on github.

Cheers!

**Comment by zafartahirov** [comment]
Make sure you enable UART on the RPi Zero. Also, this error happens when you have finger placed on scanner, but scanner returned empty or any `NACK_` error (except ` `NACK_FINGER_IS_NOT_PRESSED`). You need to print `response[0]['Parameter']` in order to find out what is really going on. The `demo.py` is not supposed to be a production code -- this is what it is called, a demo.

This package is designed to give a bridge API between a working UART and any 3rd party application. This means it assumes that everything else is working perfectly
